# Generated by Django 3.2.9 on 2021-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
