# Generated by Django 3.2.9 on 2021-12-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0004_auto_20211206_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='FloorPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='wifirooms.floorplan'),
        ),
    ]
