# Generated by Django 3.2.9 on 2021-12-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0005_alter_room_floorplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalpoint',
            name='FloorPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_points', to='wifirooms.floorplan'),
        ),
    ]
