# Generated by Django 4.0.4 on 2022-04-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0006_alter_signalpoint_floorplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signalpoint',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='signalpoint',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
