# Generated by Django 4.0.4 on 2022-05-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0007_alter_room_height_alter_room_width_alter_room_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField(default='[]')),
                ('FloorPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Routes', to='wifirooms.floorplan')),
            ],
        ),
    ]
