# Generated by Django 4.0.5 on 2022-08-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0008_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='created_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='updated_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AddField(
            model_name='signalpoint',
            name='created_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AddField(
            model_name='signalpoint',
            name='updated_at',
            field=models.DateTimeField(default='time created'),
        ),
        migrations.AlterField(
            model_name='route',
            name='FloorPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='wifirooms.floorplan'),
        ),
        migrations.AlterField(
            model_name='route',
            name='points',
            field=models.TextField(),
        ),
    ]
