# Generated by Django 4.0.5 on 2022-08-24 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0009_floorplan_created_at_floorplan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 504841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 504841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 545579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 545579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 546580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 546580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signalpoint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 546580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signalpoint',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 15, 50, 56, 546580, tzinfo=utc)),
        ),
    ]
