# Generated by Django 4.0.5 on 2022-08-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0011_alter_floorplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='created_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.195740195740195740195740195740195740]][UTC0]'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='updated_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.202301202301202301202301202301202301]][UTC0]'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.233847233847233847233847233847233847]][UTC0]'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.233847233847233847233847233847233847]][UTC0]'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.235140235140235140235140235140235140]][UTC0]'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.235140235140235140235140235140235140]][UTC0]'),
        ),
        migrations.AlterField(
            model_name='signalpoint',
            name='created_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.233847233847233847233847233847233847]][UTC0]'),
        ),
        migrations.AlterField(
            model_name='signalpoint',
            name='updated_at',
            field=models.DateTimeField(default='2022202220222022-AugAug-WedWed 1515:AugAug[:0707[.234846234846234846234846234846234846]][UTC0]'),
        ),
    ]
