# Generated by Django 4.0.5 on 2022-08-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0016_remove_floorplan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalpoint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signalpoint',
            name='updated_at',
        ),
    ]
