# Generated by Django 4.0.5 on 2022-08-24 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0017_remove_signalpoint_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalpoint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='signalpoint',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
