# Generated by Django 4.0.5 on 2022-08-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifirooms', '0018_signalpoint_created_at_signalpoint_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalpoint',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='signalpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
